worker_processes 1;

events {
    worker_connections 1024;
}

http {

    include       mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    upstream flask_servers {
        server 127.0.0.1:2813;
        server 127.0.0.1:2814;
    }

    # DOMAIN 1
    server {
        listen 80;
        server_name iris1.local;

        location / {
            proxy_pass http://flask_servers;
        }
    }

    # DOMAIN 2
    server {
        listen 80;
        server_name iris2.local;

        location / {
            proxy_pass http://flask_servers;
        }
    }

}