worker_processes auto;

events {
    worker_connections 2048;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    server {
        listen 80;
        server_name localhost;

        # STATIC FILES (FAST 🚀)
        location / {
            root /absolute/path/to/project/static;
            index index.html;
            try_files $uri /index.html;
        }

        # API CALLS → FLASK
        location /predict {
            proxy_pass http://127.0.0.1:2813;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}